### ISSUE TITLE
Kubeflow v1.8 release tracker for Nutanix Kubernetes Engine(NKE)

### ISSUE THREAD

**Issue by nagar-ajay** [nutanix/kubeflow-manifests#10]
With Kubeflow 1.8 release, the progress is tracked for the following features on Nutanix Kubernetes Engine.

Kubernetes version - 1.25, Kustomize version - 5.0.3, Nutanix Kubernetes Engine - 2.8.0

- [x] multi-user deployment with profiles
- [x] distributed training using Training operator(TFJob)
- [x] Hyperparameter optimization using Katib
- [x] Testing Inference using KServe
- [x] Workflow creation using Pipelines
- [x] e2e-mnist manifest testing
- [x] Tensorboard using object store

**Comment by nagar-ajay** [comment]
Validated the above-listed features using Kubeflow 1.8.0-RC.1

**Comment by nagar-ajay** [comment]
Validated all the features using the Kubeflow 1.8 release.
