### ISSUE TITLE
Kubeflow v1.9 release tracker for Nutanix Kubernetes Engine(NKE)

### ISSUE THREAD

**Issue by nagar-ajay** [nutanix/kubeflow-manifests#21]
With Kubeflow 1.8 release, the progress is tracked for the following features on Nutanix Kubernetes Engine.

Kubernetes version - 1.25, Kustomize version - 5.0.3, Nutanix Kubernetes Engine - 2.8.0

- [ ] multi-user deployment with profiles
- [ ] distributed training using Training operator(TFJob)
- [ ] Hyperparameter optimization using Katib
- [ ] Testing Inference using KServe
- [ ] Workflow creation using Pipelines
- [ ] e2e-mnist manifest testing
- [ ] Tensorboard using object store
