### ISSUE TITLE
Kubeflow v1.7 release tracker for Nutanix Kubernetes Engine(NKE)

### ISSUE THREAD

**Issue by nagar-ajay** [nutanix/kubeflow-manifests#6]
With Kubeflow 1.7 release, the progress is tracked for the following features on Nutanix Karbon

Kubernetes version - 1.24, Kustomize version - 5.0.1

- [x] multi-user deployment with profiles
- [x] distributed training using Training operator(TFJob)
- [x] Hyperparameter optimization using Katib
- [x] Testing Inference using KServe
- [x] Workflow creation using Pipelines
- [x] e2e-mnist manifest testing

**Comment by johnugeorge** [comment]
Need to test with Kustomise 5

**Comment by nagar-ajay** [comment]
Kubeflow manifests release [1.7.0-rc.2](https://github.com/kubeflow/manifests/releases/tag/v1.7.0-rc.2) is tested against Nutanix NKE 2.7.0 with Kubernetes 1.24
